services:
  - type: web
    name: my-django-site
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn your_project_name.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Site.settings
      - key: PYTHON_VERSION
        value: 3.12
