# Generated by Django 5.2 on 2025-04-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='/static/images/default.jpg', upload_to='static/images/'),
        ),
    ]
