# Generated by Django 5.2 on 2025-04-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.CharField(choices=[('static/images/cafe.jpg', 'cafe.jpg'), ('static/images/combo1.jpg', 'combo1.jpg'), ('static/images/fon.jpg', 'fon.jpg'), ('static/images/foto1.jpg', 'foto1.jpg'), ('static/images/foto2.jpg', 'foto2.jpg'), ('static/images/foto3.jpg', 'foto3.jpg'), ('static/images/foto4.jpg', 'foto4.jpg'), ('static/images/foto5.jpg', 'foto5.jpg'), ('static/images/foto6.jpg', 'foto6.jpg'), ('static/images/foto7.jpg', 'foto7.jpg'), ('static/images/foto8.jpg', 'foto8.jpg'), ('static/images/gorki.jpg', 'gorki.jpg'), ('static/images/instagram.png', 'instagram.png'), ('static/images/Logo128x128x.png', 'Logo128x128x.png'), ('static/images/Logo16x16.png', 'Logo16x16.png'), ('static/images/Logo32x32.png', 'Logo32x32.png'), ('static/images/Logo64x64.png', 'Logo64x64.png'), ('static/images/Logo96x96.png', 'Logo96x96.png'), ('static/images/medalyon.jpg', 'medalyon.jpg'), ('static/images/pattern.png', 'pattern.png'), ('static/images/pepperoni.jpg', 'pepperoni.jpg'), ('static/images/phone.png', 'phone.png'), ('static/images/shakur.jpg', 'shakur.jpg'), ('static/images/sobaki.jpg', 'sobaki.jpg'), ('static/images/sudak.jpg', 'sudak.jpg'), ('static/images/tiktok.png', 'tiktok.png'), ('static/images/velo.jpg', 'velo.jpg'), ('static/images/Verovochnyy_park.jpg', 'Verovochnyy_park.jpg'), ('static/images/Vodnoye_veselye.jpg', 'Vodnoye_veselye.jpg')], max_length=255),
        ),
    ]
